apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-backend
  labels:
    app: resume-backend
spec:
  template:
    metadata:
      name: resume-backend
      labels:
        app: resume-backend
    spec:
      containers:
      - name: resume-backend
        image: rustybridge/resume-backend:1.3
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: host
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: database
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: db_password
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: db_port
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: secret_key
        ports:
        - containerPort: 8000
          name: listen
  selector:
    matchLabels:
      app: resume-backend
  replicas: 2
